# Generated by Django 5.2.13 on 2026-05-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(default='', verbose_name='Hakkimizda Metni')),
            ],
            options={
                'verbose_name': 'Hakkimizda Sayfasi',
                'verbose_name_plural': 'Hakkimizda Sayfasi',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(default='', max_length=60, verbose_name='Nerden')),
                ('to_location', models.CharField(default='', max_length=60, verbose_name='Nereye')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fiyat')),
                ('currency', models.CharField(choices=[('$', '$ Dolar'), ('₺', '₺ Lira'), ('€', '€ Euro')], default='€', verbose_name='Döviz')),
            ],
            options={
                'verbose_name': 'Fiyatlar',
                'verbose_name_plural': 'Fiyatlar',
            },
        ),
    ]
