# Generated by Django 5.2.13 on 2026-05-23 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_vehicle_capacity_alter_vehicle_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Araçlarim', 'verbose_name_plural': 'Araçlarim'},
        ),
    ]
