# Generated by Django 5.2.13 on 2026-05-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_vehicle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='about_text_en',
            field=models.TextField(default='', null=True, verbose_name='Hakkimizda Metni'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='about_text_ru',
            field=models.TextField(default='', null=True, verbose_name='Hakkimizda Metni'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='about_text_tr',
            field=models.TextField(default='', null=True, verbose_name='Hakkimizda Metni'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='happy_customer',
            field=models.CharField(default='20K+', verbose_name='Memnun Musteri Sayisi'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='years_experience',
            field=models.IntegerField(default=5, verbose_name='Kac Yil Deneyiminiz Var'),
        ),
    ]
