# Generated by Django 5.2.13 on 2026-05-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_aboutus_about_text_en_aboutus_about_text_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='happy_customer',
            field=models.CharField(default='20K+', max_length=20, verbose_name='Memnun Musteri Sayisi'),
        ),
    ]
