# Generated by Django 5.2.13 on 2026-04-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('pick_up_location', models.CharField(max_length=240)),
                ('drop_off_location', models.CharField(max_length=240)),
                ('pick_up_date', models.DateTimeField()),
                ('passenger_count', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('refused', 'Reddedildi')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
