# Generated by Django 5.2.13 on 2026-04-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('full_name', 'phone')},
        ),
    ]
