# Generated by Django 5.2.13 on 2026-04-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('full_name', 'phone'), name='unique_fullname_phone', violation_error_message='Bu isim ve telefon zaten kayıtlıdır.'),
        ),
    ]
