# Generated by Django 5.2.13 on 2026-04-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sipariş', 'verbose_name_plural': 'Siparişler'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Siparişin Oluşturulduğu Tarih'),
        ),
        migrations.AlterField(
            model_name='order',
            name='drop_off_location',
            field=models.CharField(max_length=240, verbose_name='Nereye'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=40, verbose_name='İsim Soyisim'),
        ),
        migrations.AlterField(
            model_name='order',
            name='passenger_count',
            field=models.IntegerField(default=1, verbose_name='Yolcu Sayısı'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pick_up_date',
            field=models.DateTimeField(verbose_name='Tarih ve saat'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pick_up_location',
            field=models.CharField(max_length=240, verbose_name='Nereden'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('refused', 'Reddedildi')], default='pending', max_length=10, verbose_name='Sipariş Durumu'),
        ),
    ]
