# Generated by Django 5.2.13 on 2026-04-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Çalışan E-postası',
                'verbose_name_plural': 'Çalışanların E-postaları',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='İsim Soyisim'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Telefon Numarası'),
        ),
    ]
