# Generated by Django 5.2.13 on 2026-04-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_notificationemails_alter_order_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_fullname_phone',
        ),
    ]
