# Generated by Django 5.2.13 on 2026-05-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_unique_fullname_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='direction',
            field=models.CharField(choices=[('One-Way', 'Tek Yön'), ('Two-Way', 'Çift Yön')], default='One-Way', max_length=8),
        ),
        migrations.AddField(
            model_name='order',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Donuş tarih ve saati'),
        ),
    ]
