# Generated by Django 5.2.13 on 2026-05-23 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_status_order_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='direction',
        ),
    ]
